module

public import LeanJson
public import LeanSpec.Snapshot
public meta import LeanJson
public meta import LeanSpec.Snapshot

namespace LeanSpec

open LeanJson

public section

public def escapeLeanString (s : String) : String :=
    String.ofList (s.toList.flatMap fun c =>
    match c with
    | '\\' => ['\\', '\\']
    | '"' => ['\\', '"']
    | '\n' => ['\\', 'n']
    | '\t' => ['\\', 't']
    | _ => [c])

public def unescapeLeanChar : Char → Except String Char
  | 'n' => .ok '\n'
  | 't' => .ok '\t'
  | '\\' => .ok '\\'
  | '"' => .ok '"'
  | c => .error s!"unknown escape `\\{c}`"

public def emitQuoted (s : String) : String :=
  "\"" ++ escapeLeanString s ++ "\""

public def emitProofString (s : String) : String :=
  s!"⟨{emitQuoted s}, by native_decide⟩"

public def emitStrength : Strength → String
  | .shall => ".shall"
  | .must => ".must"
  | .should => ".should"

public def emitCheck : CheckStatus → String
  | .executable => ".executable"
  | .deferred reason => s!".deferred {emitProofString reason.value}"

public def emitScenario (s : Scenario) : String :=
  let given :=
    match s.given? with
    | none => "none"
    | some g => s!"some {emitProofString g.value}"
  "{\n" ++
    s!"      name := {emitProofString s.name.value}\n" ++
    s!"      given? := {given}\n" ++
    s!"      whenText := {emitProofString s.whenText.value}\n" ++
    s!"      thenText := {emitProofString s.thenText.value}\n" ++
    s!"      check := {emitCheck s.check}\n" ++
    "    }"

public def emitRequirement (r : Requirement) : String :=
  let scenarios :=
    joinSep ",\n    " (r.scenarios.toArray.toList.map emitScenario)
  "{\n" ++
    s!"    id := {emitProofString r.id.value}\n" ++
    s!"    shall := {emitProofString r.shall.value}\n" ++
    s!"    strength := {emitStrength r.strength}\n" ++
    "    scenarios := ⟨#[" ++
    (if r.scenarios.size == 0 then "" else "\n    " ++ scenarios ++ "\n    ") ++
    "], by native_decide⟩\n" ++
    "  }"

public def emitNonBlankArray (xs : Array NonBlank) : String :=
  if xs.isEmpty then "#[]"
  else "#[" ++ joinSep ", " (xs.toList.map fun n => emitProofString n.value) ++ "]"

public def emitNonEmptyNonBlank (xs : NonEmptyArray NonBlank) : String :=
  "⟨" ++ emitNonBlankArray xs.toArray ++ ", by native_decide⟩"

public def emitSurface : Surface → String
  | .web => ".web"
  | .native => ".native"

public def emitTarget : TargetLang → String
  | .lean4 => ".lean4"
  | .typescript => ".typescript"
  | .scala => ".scala"
  | .rust => ".rust"
  | .javaViaStrata => ".javaViaStrata"

public def emitDesignUnit (d : DesignUnit) : String :=
  "{\n" ++
    s!"    id := {emitProofString d.id.value}\n" ++
    s!"    surface := {emitSurface d.surface}\n" ++
    s!"    target := {emitTarget d.target}\n" ++
    s!"    targetAllowed := by native_decide\n" ++
    s!"    interfaces := {emitNonEmptyNonBlank d.interfaces}\n" ++
    s!"    functions := {emitNonBlankArray d.functions}\n" ++
    s!"    tests := {emitNonEmptyNonBlank d.tests}\n" ++
    s!"    theorems := {emitNonBlankArray d.theorems}\n" ++
    "  }"

/-- Deterministic Lean source for a snapshot. JSON remains wire-only. -/
public def emitSnapshotSource (s : SpecSnapshot) : String :=
  let reqs :=
    if s.requirements.isEmpty then "#[]"
    else
      "#[\n  " ++
        joinSep ",\n  " (s.requirements.toList.map emitRequirement) ++
        "\n]"
  let des :=
    if s.designs.isEmpty then "#[]"
    else
      "#[\n  " ++
        joinSep ",\n  " (s.designs.toList.map emitDesignUnit) ++
        "\n]"
  "-- Generated by lean-spec. Canonical spec store; JSON is transport only.\n" ++
    "import LeanSpec\n\n" ++
    "namespace LeanSpec.GeneratedSnapshot\n\n" ++
    "def snapshot : SpecSnapshot := {\n" ++
    s!"  requirements := {reqs}\n" ++
    "  uniqueIds := by native_decide\n" ++
    s!"  designs := {des}\n" ++
    "  uniqueDesignIds := by native_decide\n" ++
    "  designsLinked := by native_decide\n" ++
    "}\n\n" ++
    "end LeanSpec.GeneratedSnapshot\n"

private def skipWs : List Char → List Char
  | ' ' :: rest | '\n' :: rest | '\t' :: rest | '\r' :: rest => skipWs rest
  | cs => cs

private def eat (tok : String) (cs : List Char) : Option (List Char) :=
  let t := tok.toList
  let cs := skipWs cs
  if cs.take t.length == t then some (cs.drop t.length) else none

private def fail (detail : String) : Except DecodeError α :=
  .error (.illFormed "snapshot.lean" detail)

private def parseQuoted : List Char → Except DecodeError (String × List Char)
  | '"' :: rest =>
    let rec go (acc : List Char) : List Char → Except DecodeError (String × List Char)
      | [] => fail "unterminated string"
      | '"' :: rest => .ok (String.ofList acc.reverse, rest)
      | '\\' :: [] => fail "unterminated escape"
      | '\\' :: c :: rest =>
        match unescapeLeanChar c with
        | .error d => fail d
        | .ok u => go (u :: acc) rest
      | c :: rest => go (c :: acc) rest
    go [] rest
  | _ => fail "expected string literal"

private def parseProofString (cs : List Char) : Except DecodeError (String × List Char) := do
  let cs ← match eat "⟨" cs with
    | some cs => pure cs
    | none => fail "expected ⟨"
  let (s, cs) ← parseQuoted (skipWs cs)
  let cs ← match eat "," cs with
    | some cs => pure cs
    | none => fail "expected comma in proof string"
  let cs ← match eat "by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected `by native_decide`"
  let cs ← match eat "⟩" cs with
    | some cs => pure cs
    | none => fail "expected ⟩"
  pure (s, cs)

private def parseStrength (cs : List Char) : Except DecodeError (Strength × List Char) :=
  match eat ".shall" cs with
  | some cs => .ok (.shall, cs)
  | none =>
    match eat ".must" cs with
    | some cs => .ok (.must, cs)
    | none =>
      match eat ".should" cs with
      | some cs => .ok (.should, cs)
      | none => fail "expected strength"

private def parseCheck (cs : List Char) : Except DecodeError (CheckStatus × List Char) :=
  match eat ".executable" cs with
  | some cs => .ok (.executable, cs)
  | none =>
    match eat ".deferred" cs with
    | some cs => do
      let (reason, cs) ← parseProofString cs
      match NonBlank.parse "snapshot.lean.check.reason" reason with
      | .error e => fail e.pretty
      | .ok nb => .ok (.deferred nb, cs)
    | none => fail "expected check"

private def parseField (name : String) (cs : List Char) : Except DecodeError (List Char) := do
  let cs ← match eat (name ++ " :=") cs with
    | some cs => pure cs
    | none => fail s!"expected field `{name}`"
  pure cs

private def parseScenario (cs : List Char) : Except DecodeError (Scenario × List Char) := do
  let cs ← match eat "{" cs with
    | some cs => pure cs
    | none => fail "expected scenario `{`"
  let cs ← parseField "name" cs
  let (name, cs) ← parseProofString cs
  let cs ← parseField "given?" cs
  let (given?, cs) ←
    match eat "none" cs with
    | some cs => pure (none, cs)
    | none =>
      match eat "some" cs with
      | some cs => do
        let (g, cs) ← parseProofString cs
        match NonBlank.parse "snapshot.lean.given" g with
        | .error e => fail e.pretty
        | .ok nb => pure (some nb, cs)
      | none => fail "expected given? none/some"
  let cs ← parseField "whenText" cs
  let (whenText, cs) ← parseProofString cs
  let cs ← parseField "thenText" cs
  let (thenText, cs) ← parseProofString cs
  let cs ← parseField "check" cs
  let (check, cs) ← parseCheck cs
  let cs ← match eat "}" cs with
    | some cs => pure cs
    | none => fail "expected scenario `}`"
  match NonBlank.parse "snapshot.lean.scenario.name" name,
      NonBlank.parse "snapshot.lean.when" whenText,
      NonBlank.parse "snapshot.lean.then" thenText with
  | .ok name, .ok whenText, .ok thenText =>
    pure ({ name, given?, whenText, thenText, check }, cs)
  | .error e, _, _ | _, .error e, _ | _, _, .error e => fail e.pretty

private def parseCommaSep {α} (parseOne : List Char → Except DecodeError (α × List Char))
    (close : String) (cs : List Char) : Except DecodeError (Array α × List Char) :=
  let cs := skipWs cs
  match eat close cs with
  | some cs => .ok (#[], cs)
  | none =>
    let rec go (fuel : Nat) (acc : Array α) (cs : List Char) :
        Except DecodeError (Array α × List Char) :=
      match fuel with
      | 0 => fail "array too large"
      | n + 1 => do
        let (x, cs) ← parseOne cs
        let acc := acc.push x
        match eat "," cs with
        | some cs => go n acc cs
        | none =>
          match eat close cs with
          | some cs => .ok (acc, cs)
          | none => fail s!"expected `,` or `{close}`"
    go cs.length.succ #[] cs

private def parseScenarioArray (cs : List Char) : Except DecodeError (NonEmptyArray Scenario × List Char) := do
  let cs ← match eat "⟨#[" cs with
    | some cs => pure cs
    | none => fail "expected ⟨#["
  let (items, cs) ← parseCommaSep parseScenario "]" cs
  let cs ← match eat ", by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected `, by native_decide` after scenarios"
  let cs ← match eat "⟩" cs with
    | some cs => pure cs
    | none => fail "expected ⟩ after scenarios"
  match NonEmptyArray.ofArray "snapshot.lean.scenarios" items with
  | .error e => fail e.pretty
  | .ok arr => .ok (arr, cs)

private def parseRequirement (cs : List Char) : Except DecodeError (Requirement × List Char) := do
  let cs ← match eat "{" cs with
    | some cs => pure cs
    | none => fail "expected requirement `{`"
  let cs ← parseField "id" cs
  let (id, cs) ← parseProofString cs
  let cs ← parseField "shall" cs
  let (shall, cs) ← parseProofString cs
  let cs ← parseField "strength" cs
  let (strength, cs) ← parseStrength cs
  let cs ← parseField "scenarios" cs
  let (scenarios, cs) ← parseScenarioArray cs
  let cs ← match eat "}" cs with
    | some cs => pure cs
    | none => fail "expected requirement `}`"
  match RequirementId.parse "snapshot.lean.id" id, NonBlank.parse "snapshot.lean.shall" shall with
  | .ok id, .ok shall =>
    pure ({ id, shall, strength, scenarios }, cs)
  | .error e, _ | _, .error e => fail e.pretty

private def parseNonBlankItem (cs : List Char) : Except DecodeError (NonBlank × List Char) := do
  let (s, cs) ← parseProofString cs
  match NonBlank.parse "snapshot.lean.name" s with
  | .ok nb => pure (nb, cs)
  | .error e => fail e.pretty

private def parseNonBlankArray (cs : List Char) : Except DecodeError (Array NonBlank × List Char) :=
  match eat "#[]" cs with
  | some cs => .ok (#[], cs)
  | none => do
    let cs ← match eat "#[" cs with
      | some cs => pure cs
      | none => fail "expected non-blank array"
    parseCommaSep parseNonBlankItem "]" cs

private def parseNonEmptyNonBlank (cs : List Char) :
    Except DecodeError (NonEmptyArray NonBlank × List Char) := do
  let cs ← match eat "⟨" cs with
    | some cs => pure cs
    | none => fail "expected ⟨ before non-blank array"
  let (items, cs) ← parseNonBlankArray cs
  let cs ← match eat ", by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected `, by native_decide` after names"
  let cs ← match eat "⟩" cs with
    | some cs => pure cs
    | none => fail "expected ⟩ after names"
  match NonEmptyArray.ofArray "snapshot.lean.names" items with
  | .error e => fail e.pretty
  | .ok arr => .ok (arr, cs)

private def parseSurfaceLit (cs : List Char) : Except DecodeError (Surface × List Char) :=
  match eat ".web" cs with
  | some cs => .ok (.web, cs)
  | none =>
    match eat ".native" cs with
    | some cs => .ok (.native, cs)
    | none => fail "expected surface"

private def parseTargetLit (cs : List Char) : Except DecodeError (TargetLang × List Char) :=
  match eat ".lean4" cs with
  | some cs => .ok (.lean4, cs)
  | none =>
    match eat ".typescript" cs with
    | some cs => .ok (.typescript, cs)
    | none =>
      match eat ".scala" cs with
      | some cs => .ok (.scala, cs)
      | none =>
        match eat ".rust" cs with
        | some cs => .ok (.rust, cs)
        | none =>
          match eat ".javaViaStrata" cs with
          | some cs => .ok (.javaViaStrata, cs)
          | none => fail "expected target language"

private def parseDesignUnit (cs : List Char) : Except DecodeError (DesignUnit × List Char) := do
  let cs ← match eat "{" cs with
    | some cs => pure cs
    | none => fail "expected design `{`"
  let cs ← parseField "id" cs
  let (id, cs) ← parseProofString cs
  let cs ← parseField "surface" cs
  let (surface, cs) ← parseSurfaceLit cs
  let cs ← parseField "target" cs
  let (target, cs) ← parseTargetLit cs
  let cs ← parseField "targetAllowed" cs
  let cs ← match eat "by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected targetAllowed proof"
  let cs ← parseField "interfaces" cs
  let (interfaces, cs) ← parseNonEmptyNonBlank cs
  let cs ← parseField "functions" cs
  let (functions, cs) ← parseNonBlankArray cs
  let cs ← parseField "tests" cs
  let (tests, cs) ← parseNonEmptyNonBlank cs
  let cs ← parseField "theorems" cs
  let (theorems, cs) ← parseNonBlankArray cs
  let cs ← match eat "}" cs with
    | some cs => pure cs
    | none => fail "expected design `}`"
  match RequirementId.parse "snapshot.lean.design.id" id with
  | .ok id =>
    if hAllowed : AllowedTarget surface target then
      pure ({ id, surface, target, targetAllowed := hAllowed,
              interfaces, functions, tests, theorems }, cs)
    else
      fail "design target is not allowed for its surface"
  | .error e => fail e.pretty

/-- Parse source produced by `emitSnapshotSource`. Any other shape is refused. -/
public def parseSnapshotSource (src : String) : Except DecodeError SpecSnapshot := do
  let cs := skipWs src.toList
  let cs ← match eat "-- Generated by lean-spec. Canonical spec store; JSON is transport only." cs with
    | some cs => pure cs
    | none => fail "missing generated header"
  let cs ← match eat "import LeanSpec" cs with
    | some cs => pure cs
    | none => fail "expected `import LeanSpec`"
  let cs ← match eat "namespace LeanSpec.GeneratedSnapshot" cs with
    | some cs => pure cs
    | none => fail "expected generated namespace"
  let cs ← match eat "def snapshot : SpecSnapshot := {" cs with
    | some cs => pure cs
    | none => fail "expected `def snapshot`"
  let cs ← parseField "requirements" cs
  let (requirements, cs) ←
    match eat "#[]" cs with
    | some cs => pure (#[], cs)
    | none => do
      let cs ← match eat "#[" cs with
        | some cs => pure cs
        | none => fail "expected requirement array"
      parseCommaSep parseRequirement "]" cs
  let cs ← parseField "uniqueIds" cs
  let cs ← match eat "by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected uniqueIds proof"
  let cs ← parseField "designs" cs
  let (designs, cs) ←
    match eat "#[]" cs with
    | some cs => pure (#[], cs)
    | none => do
      let cs ← match eat "#[" cs with
        | some cs => pure cs
        | none => fail "expected design array"
      parseCommaSep parseDesignUnit "]" cs
  let cs ← parseField "uniqueDesignIds" cs
  let cs ← match eat "by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected uniqueDesignIds proof"
  let cs ← parseField "designsLinked" cs
  let cs ← match eat "by native_decide" cs with
    | some cs => pure cs
    | none => fail "expected designsLinked proof"
  let cs ← match eat "}" cs with
    | some cs => pure cs
    | none => fail "expected snapshot `}`"
  let cs ← match eat "end LeanSpec.GeneratedSnapshot" cs with
    | some cs => pure cs
    | none => fail "expected generated namespace end"
  if !(skipWs cs).isEmpty then
    fail "trailing content after generated snapshot"
  else
    match SpecSnapshot.ofDesigned "snapshot.lean.requirements" requirements designs with
    | .ok s => .ok s
    | .error e => fail e.pretty

#guard
  let empty : SpecSnapshot := SpecSnapshot.empty
  match parseSnapshotSource (emitSnapshotSource empty) with
  | .ok s => s == empty
  | .error _ => false

/-- Emission depends only on the requirement and design lists, not on proof terms. -/
public theorem emitSnapshotSource_of_payload {s t : SpecSnapshot}
    (hReq : s.requirements = t.requirements) (hDes : s.designs = t.designs) :
    emitSnapshotSource s = emitSnapshotSource t := by
  cases s with
  | mk reqs _ des _ _ =>
    cases t with
    | mk reqs' _ des' _ _ =>
      cases hReq
      cases hDes
      rfl

/-- Emission depends only on the requirement list when designs match. -/
public theorem emitSnapshotSource_of_requirements {s t : SpecSnapshot}
    (h : s.requirements = t.requirements) (hDes : s.designs = t.designs) :
    emitSnapshotSource s = emitSnapshotSource t :=
  emitSnapshotSource_of_payload h hDes

/-- Empty snapshot roundtrips through the generated-source parser. -/
public theorem parse_emit_empty_isOk :
    (parseSnapshotSource (emitSnapshotSource SpecSnapshot.empty)).isOk = true := by
  native_decide

#guard
  let r : Requirement := {
    id := ⟨"quote.line", by native_decide⟩
    shall := ⟨"say \"hi\"\nthere", by native_decide⟩
    scenarios := ⟨#[{
      name := ⟨"n", by native_decide⟩
      given? := some ⟨"g", by native_decide⟩
      whenText := ⟨"w", by native_decide⟩
      thenText := ⟨"t", by native_decide⟩
      check := .deferred ⟨"later", by native_decide⟩
    }], by native_decide⟩
  }
  let snap : SpecSnapshot := { requirements := #[r], uniqueIds := by native_decide }
  match parseSnapshotSource (emitSnapshotSource snap) with
  | .ok s => s == snap && emitSnapshotSource s == emitSnapshotSource snap
  | .error _ => false

end

end LeanSpec
